site_name: Traquito - WSPR Pico Balloons
site_url: https://traquito.github.io/

repo_name: traquito/traquito.github.io
repo_url: https://github.com/traquito/traquito.github.io
edit_uri: blob/main/docs/

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  favicon: favicon.ico
  logo: logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    size: large
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.indexes  # consolidates nav
    - toc.follow # scroll toc with page you're looking at
    - content.code.copy   # copy code button
    - content.code.select # link to range of code (insiders, not working)
    - content.code.annotate # annotate code

plugins:
  - search
  - blog:
      blog_dir: "updates"
      blog_toc: true
  - git-revision-date-localized:
      type: date

extra:
  analytics:
    provider: google
    property: G-07H1M3KB40

markdown_extensions: 
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.superfences
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets


nav:
  - Home: README.md
  - Jetpack WSPR Tracker:
    - tracker/README.md
    - Jetpack Technical Details: tracker/V1/README.md
  - Solar System: solar/README.md
  - Spot Search: search/spots/dashboard/example/README.md
  - Channel Map: 
    - channelmap/README.md
    - Channel Map Help: channelmap/help/README.md
  - Tracker GUI:
    - trackergui/README.md
    - Tracker GUI Help: trackergui/help/README.md
  - Wind-O-Matic 5000: WOM5000/README.md
  - Pro Zone:
    - pro/README.md
    - Decode: pro/decode/README.md
    - Query wspr.live: pro/query/README.md
    - API Mode:
      - pro/apimode/README.md
      - GPS Test Demo: pro/apimode/gps/README.md
    - Tracker Hacker: pro/trackerhacker/README.md
    - WSPR Telemetry:
      - pro/telemetry/README.md
      - Basic Telemetry: pro/telemetry/basic/README.md
      - Extended Telemetry: pro/telemetry/extended/README.md
      - Channels: pro/telemetry/channels/README.md
      - Programming Library: pro/telemetry/code/README.md
      - History: pro/telemetry/history/README.md
  - FAQ:
    - faq/README.md
    - About: faq/about/README.md
    - Big Idea: faq/bigidea/README.md
    - Site Relationships: faq/sites/README.md
    - Buying Balloons: faq/balloons/buying/README.md
    - JLCPCB Orders:
      - faq/jlcpcb/README.md
      - Preordering Parts: faq/jlcpcb/preorder/README.md
    - Setup WSPR Reception: faq/receiving/README.md
    - Contact: faq/contact/README.md
  - Updates: updates/index.md